image: Ubuntu  # образ для сборки

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  java -jar ./artifact/app-ibank.jar -P:profile=test &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info -Dselenide.headless=true